pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView


urlpatterns = [
    path('about/', AboutPageView.as_view(), name='about'),
    path('', HomePageView.as_view(), name='home'),
]

posts/urls.py
from django.urls import path

from .views import (
    IndexView,
    PostDetailView,
    CategoryListView,
    CategoryPostView,
    SearchView,
    SearchPostView,
)


app_name = 'posts'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<uuid:pk>', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<str:category_slug>/', CategoryPostView.as_view(), name='category_post'),
    path('search/', SearchView.as_view(), name='search'),
    path('search_post/', SearchPostView.as_view(), name='search_post'),
]

pages/models.py
from django.db import models

# Create your models here.

posts/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)
    content = models.TextField()
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post_detail', args=[self.id])


class ContentImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.PROTECT)
    content_image = models.ImageField(upload_to='post_content_images/')

users/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


class CustomUserManager(UserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'
        ),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space inbetween.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """
        if other application get access to username, return the email for the user.
        """
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('email', )


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = '__all__'

pages/views.py
from django.views.generic import TemplateView, ListView

from posts.models import Post


class HomePageView(ListView):
    model = Post
    template_name = 'home.html'
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.order_by('-created_at')[:10]


class AboutPageView(TemplateView):
    template_name = 'about.html'

posts/views.py
from django.db.models import Count, Q
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404

from posts.models import Post, Category


class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'

    def get_object(self, queryset=None):
        post = super().get_object(queryset=queryset)
        if not post.is_public and not self.request.user.is_authenticated:
            raise Http404
        return post


class IndexView(ListView):
    model = Post
    template_name = 'posts/index.html'
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.order_by('-created_at')[:10]


class CategoryListView(ListView):
    queryset = Category.objects.annotate(
        num_posts=Count('post', filter=Q(post__is_public=True))
    )


class CategoryPostView(ListView):
    model = Post
    template_name = 'posts/category_post.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class SearchView(TemplateView):
    template_name = 'posts/search.html'


class SearchPostView(ListView):
    model = Post
    template_name = 'posts/search_post.html'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        lookups = (
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(category__name__icontains=query)
        )
        if query is not None:
            qs = super().get_queryset().filter(lookups).distinct()
            return qs
        qs = super().get_queryset()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context

users/views.py
from django.shortcuts import render

# Create your views here.

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}VIFE{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="{% block description %}{% endblock description%}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
        {% include 'snippets/header.html' %}
        {% block content %}
        {% endblock content %}
        {% include 'snippets/footer.html' %}
        {% block javascript %}
        <script src="{% static 'js/base.js' %}"></script>
        {% endblock javascript %}
    </body>
</html>

templates/about.html
{% extends '_base.html' %}

{% block title %}about{% endblock title%}

{% block content %}
<div class="container">
  <h1>about VIFE</h1>
</div>
{% endblock content %}

templates/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}home{% endblock %}


{% block content %}
<div class="container">
  <section id="posts">
      <h2 class="category-title">LATEST POSTS</h2>
      <div class="posts-container">
        {% include "snippets/main_post_list.html" %}
      </div>
  </section>
</div>
{% endblock content %}

templates/posts/category_list.html
{% extends '_base.html' %}

{% block title %}Category List{% endblock title %}

{% block content %}
<div class="container">
    <h2 class="category-title">Category List</h2>
    <div class="subclass">
        <main class="subclass-list">
            <ul>
                {% for category in object_list %}
                    <li><a href="{% url 'posts:category_post' category.slug %}">{{ category.name }} ({{ category.num_posts }})</a></li>
                {% empty %}
                    <li>カテゴリはありません。</li>
                {% endfor %}
            </ul>
        </main>
        <aside class="sidebar">
            {% include "snippets/sidebar.html" %}
        </aside>
    </div>
</div>
{% endblock content %}

templates/posts/category_post.html
{% extends '_base.html' %}

{% block title %}"{{ category.name }}" POSTS LIST{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="category-title">"{{ category.name }}" POSTS LIST</h1>
    <div class="blog-top">
        <main class="main-content">
            {% include "snippets/main_post_list.html" %}
            {% include "snippets/pagination.html" %}
        </main>
        <aside class="sidebar">
            {% include "snippets/sidebar.html" %}
        </aside>
    </div>
</div>
{% endblock content %}

templates/posts/index.html
{% extends '_base.html' %}

{% block title %}POSTS LIST{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="category-title">POSTS LIST</h1>
    <div class="blog-top">
        <main class="main-content">
            {% include "snippets/main_post_list.html" %}
            {% include "snippets/pagination.html" %}
        </main>
        <aside class="sidebar">
            {% include "snippets/sidebar.html" %}
        </aside>
    </div>
</div>
{% endblock content %}

templates/posts/post_detail.html
{% extends '_base.html' %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
<div class="container">
    <div class="post-detail-top">
      <main class="post-detail">
        <h1>{{ post.title }}</h1>
        <div class="post-detail-subhead">
            <p class="post-detail-category">category: <a href="{% url 'posts:category_post' post.category.slug %}">{{ post.category.name }}</a></p>
        </div>
        <hr>
        {{ post.content|safe }}
      </main>
      <aside class="sidebar">
        {% include "snippets/sidebar.html" %}
      </aside>
    </div>
</div>
{% endblock content %}

templates/posts/search.html
{% extends '_base.html' %}

{% block title %}Search Post{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="category-title">Search</h1>
    <div class="search-top">
        <main class="search">
            {% include 'snippets/search_form.html' %}
        </main>
        <aside class="sidebar">
            {% include 'snippets/sidebar.html' %}
        </aside>
    </div>
</div>
{% endblock content %}

templates/posts/search_post.html
{% extends '_base.html' %}

{% block title %}{% if query %}{{ query }}{% endif %} | {{ block.super }}{% endblock %}
{% block descripton %}検索ワード「{% if query %}{{ query }}{% endif %}」での検索結果ページです。{% endblock %}

{% block content %}
<div class="container">
    <h1 class="category-title">「{% if query %}{{ query }}{% endif %}」の検索結果 ({{ page_obj.end_index }} posts)</h1>

    <div class="blog-top">
        <main class="main-content">
            {% include "snippets/main_post_list.html" %}
            {% include "snippets/pagination.html" %}
        </main>
        <aside class="sidebar">
            {% include "snippets/sidebar.html" %}
        </aside>
    </div>
</div>
{% endblock content %}

templates/snippets/footer.html
<footer>
    <div class="footer-menu">
        <nav>
            <ul>
                <li><a href="{% url 'about' %}" class="about">about</a></li>
                <li><a href="#" class="contact">contact</a></li>
                <li><a href="#" class="policy">privacy policy</a></li>
            </ul>
        </nav>
    </div>
</footer>

templates/snippets/header.html
<header>
    <div class="logo">
        <h1><a href="{% url 'home' %}">VIFE</a></h1>
    </div>
    <div class="pc-menu" ontouchstart="">
        <nav>
            <ul>
                <li class="menu-list">
                    <h3>POSTS</h3>
                    <ul class="submenu posts-submenu">
                        <li><a href="{% url 'posts:index' %}">POST一覧</a></li>
                        <li><a href="{% url 'posts:category_list' %}">Categoryから探す</a></li>
                        <li><a href="{% url 'posts:search' %}">キーワード検索</a></li>
                    </ul>
                </li>
                <li class="menu-list">
                    <h3>TAGS</h3>
                    <ul class="submenu">
                    <li><a href="{% url 'home' %}">coming soon</a></li>
               </ul>
                </li>
                <li class="menu-list">
                    <h3>MAP</h3>
                    <ul class="submenu">
                    <li><a href="{% url 'home' %}">coming soon</a></li>
               </ul>
                </li>
            </ul>
        </nav>
    </div>
    <div class="sp-menu">
        <span class="material-icons" id="open">menu</span>
    </div>
</header>

<div class="overlay" ontouchstart="">
    <span class="material-icons" id="close">close</span>
    <nav>
        <ul>
            <li class="menu-list">
                <h3>POSTS</h3>
                <ul class="submenu posts-submenu">
                    <li><a href="{% url 'posts:index' %}">POST一覧</a></li>
                    <li><a href="{% url 'posts:category_list' %}">Categoryから探す</a></li>
                    <li><a href="{% url 'posts:search' %}">キーワード検索</a></li>
                </ul>
            </li>
           <li class="menu-list">
               <h3>TAGS</h3>
               <ul class="submenu">
                    <li><a href="{% url 'home' %}">coming soon</a></li>
               </ul>
           </li>
           <li class="menu-list">
               <h3>MAP</h3>
               <ul class="submenu">
                    <li><a href="{% url 'home' %}">coming soon</a></li>
               </ul>
           </li>
        </ul>
    </nav>
</div>

templates/snippets/main_post_list.html
<div class="post-container">
    {% for post in object_list %}
        {% if post.is_public %}
          <article class="post-block">
            <a href="{{ post.get_absolute_url }}" class="post-all-a"></a>
            {% if post.image %}
            <img src="{{ post.image.url }}" alt="{{ post.title }}">
            {% endif %}
            <div class="post-head">
                <p>{{ post.category.name }}</p>
                <h1>{{ post.title }}</h1>
            </div>
          </article>
        {% endif %}
    {% empty %}
        <p>No Posts</p>
    {% endfor %}
</div>

templates/snippets/pagination.html
{% if is_paginated %}
<nav>
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">前へ</a>
    {% endif %}

    {% for num in paginator.page_range %}
    {% if page_obj.number == num %}
    <span>{{ num }}</span>
    {% else %}
    <a href="?page={{ num }}{% if query %}&q={{ query }}{% endif %}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a href="?page{{ page_obj.next_page_number }}{% if query %}&q={{ query }}{% endif %}">次へ</a>
    {% endif %}
</nav>
{% endif %}

templates/snippets/search_form.html
<form action="{% url 'posts:search_post' %}" method="GET">
    <input type="search" name="q" value="{{ request.GET.q }}" placeholder="Search" aria-label="Search" required>
    <button type="submit" class="btn">Search</button>
</form>

templates/snippets/sidebar.html
<div class="card">
    <div class="card-header">Search</div>
    <div class="search-content">
        {% include 'snippets/search_form.html' %}
    </div>
</div>

<div class="card">
  <div class="card-header">
    Category
  </div>
  <ul class="list-group">
    {% for category in categories|dictsortreversed:"num_posts"|slice:":5" %}
    <li class="list-group-item">
      <a href="{% url 'posts:category_post' category.slug %}" class="card-link">{{ category.name }} ({{ category.num_posts }})</a>
    </li>
    {% endfor %}
  </ul>
  <div class="card-body">
    <a href="{% url 'posts:category_list' %}" class="card-link">カテゴリ一覧</a>
  </div>
</div>